### ISSUE TITLE
弃用咪咕音乐接口

### ISSUE THREAD

**Issue by rakuzen25** [JumpAlang/Jusic-Serve-Houses#15]
尝试搜索咪咕的时候会报错。

后端日志：
```
2022-05-02 14:16:22.682 DEBUG 7 --- [boundChannel-19] .WebSocketAnnotationMethodMessageHandler : Searching methods to handle SEND /music/search session=53sxqe1u, lookupDestination='/music/search'
2022-05-02 14:16:22.682 DEBUG 7 --- [boundChannel-20] org.springframework.web.SimpLogging      : Processing SEND /music/search session=53sxqe1u
2022-05-02 14:16:22.688 DEBUG 7 --- [boundChannel-19] .WebSocketAnnotationMethodMessageHandler : Invoking MusicController#search[3 args]
2022-05-02 14:16:23.649  INFO 7 --- [boundChannel-19] c.s.jusic.service.imp.MusicServiceImpl   : mg音乐搜索接口异常, 请检查音乐服务
2022-05-02 14:16:23.650  INFO 7 --- [boundChannel-19] c.s.jusic.controller.MusicController     : session: 53sxqe1u 尝试搜索音乐, 关键字: test, 即将向该用户推送结果
```

API日志：
```
POST /search?keyword=test&pageNo=1&pageSize=10 200 891.652 ms - 69
(node:68) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'musics' of undefined
    at Object./ [as func] (/app/MiguMusicApi/routes/search.js:41:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:68) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

感觉有可能是隔壁MiguMusicApi的问题……不知道能否复现？

**Comment by rakuzen25** [comment]
另外“禁歌”API貌似根本没有返回结果。

好像music.alang.run也有这两个问题，所以应该不是我的部署问题……

**Comment by JumpAlang** [comment]
咪咕api接口已经弃用了，
禁歌目前只有李志跟陈升的部分歌曲，你可以搜索李志试下

**Comment by rakuzen25** [comment]
啊……难怪。

后期有移除的打算吗？

**Comment by JumpAlang** [comment]
嗯！后期会移除
