### ISSUE TITLE
部署到本地一直报错，然后点歌都没有响应

### ISSUE THREAD

**Issue by liuyang-zhituanbox** [JumpAlang/Jusic-Serve-Houses#24]
## 错误日志

```log
2022-11-16 10:38:10.579  INFO 7 --- [MessageBroker-4] c.s.jusic.service.imp.MusicServiceImpl   : 选歌列表为空, 已从默认列表中随机选择一首: null
2022-11-16 10:38:10.579 ERROR 7 --- [MessageBroker-4] com.scoder.jusic.job.MusicJob            : houseName:内鬼集结地,houseId:5Zr1AEXD,message:[null]
2022-11-16 10:38:11.078  INFO 7 --- [MessageBroker-2] com.scoder.jusic.job.MusicJob            : 推送开关开启, 原因: 首次启动内鬼集结地
2022-11-16 10:38:11.078  INFO 7 --- [MessageBroker-2] com.scoder.jusic.job.MusicJob            : 检测到推送开关已开启
2022-11-16 10:38:11.079  INFO 7 --- [MessageBroker-2] c.s.jusic.service.imp.MusicServiceImpl   : 选歌列表为空, 已从默认列表中随机选择一首: null
2022-11-16 10:38:11.079 ERROR 7 --- [MessageBroker-2] com.scoder.jusic.job.MusicJob            : houseName:内鬼集结地,houseId:5Zr1AEXD,message:[null]
2022-11-16 10:38:11.578  INFO 7 --- [MessageBroker-2] com.scoder.jusic.job.MusicJob            : 推送开关开启, 原因: 首次启动内鬼集结地
2022-11-16 10:38:11.578  INFO 7 --- [MessageBroker-2] com.scoder.jusic.job.MusicJob            : 检测到推送开关已开启
2022-11-16 10:38:11.579  INFO 7 --- [MessageBroker-2] c.s.jusic.service.imp.MusicServiceImpl   : 选歌列表为空, 已从默认列表中随机选择一首: null
2022-11-16 10:38:11.579 ERROR 7 --- [MessageBroker-2] com.scoder.jusic.job.MusicJob            : houseName:内鬼集结地,houseId:5Zr1AEXD,message:[null]
2022-11-16 10:38:12.078  INFO 7 --- [MessageBroker-2] com.scoder.jusic.job.MusicJob            : 推送开关开启, 原因: 首次启动内鬼集结地
2022-11-16 10:38:12.079  INFO 7 --- [MessageBroker-2] com.scoder.jusic.job.MusicJob            : 检测到推送开关已开启
2022-11-16 10:38:12.079  INFO 7 --- [MessageBroker-2] c.s.jusic.service.imp.MusicServiceImpl   : 选歌列表为空, 已从默认列表中随机选择一首: null
2022-11-16 10:38:12.080 ERROR 7 --- [MessageBroker-2] com.scoder.jusic.job.MusicJob            : houseName:内鬼集结地,houseId:5Zr1AEXD,message:[null]
2022-11-16 10:38:12.578  INFO 7 --- [MessageBroker-2] com.scoder.jusic.job.MusicJob            : 推送开关开启, 原因: 首次启动内鬼集结地
2022-11-16 10:38:12.578  INFO 7 --- [MessageBroker-2] com.scoder.jusic.job.MusicJob            : 检测到推送开关已开启
2022-11-16 10:38:12.579  INFO 7 --- [MessageBroker-2] c.s.jusic.service.imp.MusicServiceImpl   : 选歌列表为空, 已从默认列表中随机选择一首: null
2022-11-16 10:38:12.579 ERROR 7 --- [MessageBroker-2] com.scoder.jusic.job.MusicJob            : houseName:内鬼集结地,houseId:5Zr1AEXD,message:[null]
2022-11-16 10:38:13.078  INFO 7 --- [MessageBroker-2] com.scoder.jusic.job.MusicJob            : 推送开关开启, 原因: 首次启动内鬼集结地
2022-11-16 10:38:13.078  INFO 7 --- [MessageBroker-2] com.scoder.jusic.job.MusicJob            : 检测到推送开关已开启
2022-11-16 10:38:13.079  INFO 7 --- [MessageBroker-2] c.s.jusic.service.imp.MusicServiceImpl   : 选歌列表为空, 已从默认列表中随机选择一首: null
2022-11-16 10:38:13.080 ERROR 7 --- [MessageBroker-2] com.scoder.jusic.job.MusicJob            : houseName:内鬼集结地,houseId:5Zr1AEXD,message:[null]

```
### 界面点歌也没有反应
![image](https://user-images.githubusercontent.com/39367209/202158881-6e144b7e-da1f-4b9f-aa4b-73ae5c811e4d.png)

**Comment by JumpAlang** [comment]
推荐使用docker-compose一键部署，docker-compose.yml脚本：
```
version: "3"
services:
  service_redis:
    restart: always
    #ports:
    #  - 6379:6379
    image: redis
    container_name: redis
    environment:
      - TZ=Asia/Shanghai
    command: redis-server
    volumes:
      - /root/docker/redis/data:/data  #redis数据挂载到本地
  service_jusicMusicApi:
    image: jumpalang/jusic_music_api:1.6
    environment:
      - QQ=1040927107 #qq号
    container_name: jusicMusicApi
    ports:
      - "3000:3000"
      - "3300:3300"
      - "3400:3400"
      - "8081:8081"
    restart: always
  service_jusicServeHouses:
    container_name: jusicServeHouses
    image: jumpalang/jusic_serve_houses:2.4
    environment:
      - MusicApi=http://jusicMusicApi  #必须与service_jusicMusicApi的container_name一致
      - APIUSER=admin  #api认证接口用户名
      - APIPWD=123456  #api认证接口密码
      - ServerJUrl=https://sc.ftqq.com/SCU64668T909ada7955daadfb64d5e7652b93fb135dad06e659369.send #server酱消息接口，用户@管理员时会通知微信
      - IpHouse=128
      - HouseSize=128
      - MiniId=wx693312f83f255cf3
      - MiniSecrect=xxxxxxxxx
      - RoleRootPassword=123456
    ports:
      - "8080:8888"
    depends_on:
      - service_redis
      - service_jusicMusicApi
    restart: always

**Comment by liuyang-zhituanbox** [comment]
就是通过你这种方式部署的，好像如果进入空房间，没有加载出来默认推荐，就会一直报错，然后导致后续功能全部不能使用

**Comment by JumpAlang** [comment]
docker-compose上面一些容器的版本有修改了，参照我上份再重新部署看下

**Comment by liuyang-zhituanbox** [comment]
问题照旧，好像是因为默认列表没歌的原因，我通过admin加了默认歌单进去之后又可以了。但是不确定为什么会这样

**Comment by liuyang-zhituanbox** [comment]
有空指针
```
2022-11-16 11:17:29.316  INFO 7 --- [boundChannel-74] c.s.jusic.controller.MusicController     : 收到点歌请求: 不该,1978260557
2022-11-16 11:17:29.362  INFO 7 --- [MessageBroker-1] com.scoder.jusic.job.MusicJob            : 推送开关开启, 原因: 首次启动内鬼集结地
2022-11-16 11:17:29.362  INFO 7 --- [MessageBroker-1] com.scoder.jusic.job.MusicJob            : 检测到推送开关已开启
2022-11-16 11:17:29.363  INFO 7 --- [MessageBroker-1] c.s.jusic.service.imp.MusicServiceImpl   : 选歌列表为空, 已从默认列表中随机选择一首: null
2022-11-16 11:17:29.363 ERROR 7 --- [MessageBroker-1] com.scoder.jusic.job.MusicJob            : houseName:内鬼集结地,houseId:5Zr1AEXD,message:[null]
2022-11-16 11:17:29.422  WARN 7 --- [boundChannel-74] o.a.h.c.protocol.ResponseProcessCookies  : Invalid cookie header: "Set-Cookie: NMTID=00OPvSOzfpGDxtM5U1ohR1fsujKtZQAAAGEgCiCvw; Max-Age=315360000; Expires=Sat, 13 Nov 2032 11:17:29 GMT; Path=/;". Invalid 'expires' attribute: Sat, 13 Nov 2032 11:17:29 GMT
2022-11-16 11:17:29.522  WARN 7 --- [boundChannel-74] o.a.h.c.protocol.ResponseProcessCookies  : Invalid cookie header: "Set-Cookie: NMTID=00O6l9IsjOCA0naM0VcikrlCZw-u3wAAAGEgCiDHQ; Max-Age=315360000; Expires=Sat, 13 Nov 2032 11:17:29 GMT; Path=/;". Invalid 'expires' attribute: Sat, 13 Nov 2032 11:17:29 GMT
2022-11-16 11:17:29.628  WARN 7 --- [boundChannel-74] o.a.h.c.protocol.ResponseProcessCookies  : Invalid cookie header: "Set-Cookie: NMTID=00O_AUx5bz1jK_BlUBJmipPZ7BkSkIAAAGEgCiDig; Max-Age=315360000; Expires=Sat, 13 Nov 2032 11:17:29 GMT; Path=/;". Invalid 'expires' attribute: Sat, 13 Nov 2032 11:17:29 GMT
2022-11-16 11:17:29.630 DEBUG 7 --- [boundChannel-74] .WebSocketAnnotationMethodMessageHandler : Searching methods to handle NullPointerException
2022-11-16 11:17:29.630 ERROR 7 --- [boundChannel-74] .WebSocketAnnotationMethodMessageHandler : Unhandled exception from message handler method

java.lang.NullPointerException: null
	at com.scoder.jusic.service.imp.MusicServiceImpl.isPicked(MusicServiceImpl.java:1252)
	at com.scoder.jusic.controller.MusicController.pick(MusicController.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:171)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:120)
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMatch(AbstractMethodMessageHandler.java:565)
	at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:511)
	at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:94)
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessageInternal(AbstractMethodMessageHandler.java:520)
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessage(AbstractMethodMessageHandler.java:454)
	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:144)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2022-11-16 11:17:29.862  INFO 7 --- [MessageBroker-3] com.scoder.jusic.job.MusicJob            : 推送开关开启, 原因: 首次启动内鬼集结地
2022-11-16 11:17:29.862  INFO 7 --- [MessageBroker-3] com.scoder.jusic.job.MusicJob            : 检测到推送开关已开启
2022-11-16 11:17:29.863  INFO 7 --- [MessageBroker-3] c.s.jusic.service.imp.MusicServiceImpl   : 选歌列表为空, 已从默认列表中随机选择一首: null
```

**Comment by JumpAlang** [comment]
如果音乐服务不正常就会抓取不到音乐，你可以看下音乐服务是否正常

**Comment by liuyang-zhituanbox** [comment]
音乐服务没有看到什么异常，主要是如果默认的列表没有推送到歌曲时，我在聊天窗点歌也会失效。

**Comment by JumpAlang** [comment]
启动时，爬取热门默认列表歌曲没成功导致，检查下音乐服务api

**Comment by adminlove520** [comment]
MiniId=wx693312f83f255cf3
      - MiniSecrect=xxxxxxxxx
      请问这两个参数啥意思呀

**Comment by JumpAlang** [comment]
> MiniId=wx693312f83f255cf3 - MiniSecrect=xxxxxxxxx 请问这两个参数啥意思呀

这个是针对微信小程序的，没有可以不配置，没配置则分离的时候 不会生成小程序码

**Comment by adminlove520** [comment]
> > MiniId=wx693312f83f255cf3 - MiniSecrect=xxxxxxxxx 请问这两个参数啥意思呀
> 
> 这个是针对微信小程序的，没有可以不配置，没配置则分离的时候 不会生成小程序码

请问 页面的话 在哪里改呀
