### ISSUE TITLE
AttributeError: module 'six' has no attribute 'ensure_text'

### ISSUE THREAD

**Issue by YuLong-Liang** [JumpAlang/Jusic-Serve-Houses#47]
克隆项目后，执行命令
`docker-compose up -d`
提示下面错误。
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.25.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 72, in main
    command()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 125, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 53, in project_from_options
    return get_project(
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 151, in get_project
    return Project.from_config(
  File "/usr/lib/python3/dist-packages/compose/project.py", line 102, in from_config
    service_networks = get_networks(service_dict, networks)
  File "/usr/lib/python3/dist-packages/compose/network.py", line 320, in get_networks
    networks[network.true_name] = netdef
  File "/usr/lib/python3/dist-packages/compose/network.py", line 125, in true_name
    self._set_legacy_flag()
  File "/usr/lib/python3/dist-packages/compose/network.py", line 146, in _set_legacy_flag
    data = self.inspect(legacy=True)
  File "/usr/lib/python3/dist-packages/compose/network.py", line 106, in inspect
    return self.client.inspect_network(self.legacy_full_name)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/network.py", line 212, in inspect_network
    res = self._get(url, params=params)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 230, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/.local/lib/python3.8/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/.local/lib/python3.8/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/home/.local/lib/python3.8/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/.local/lib/python3.8/site-packages/requests/models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "/home/.local/lib/python3.8/site-packages/requests/models.py", line 433, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "/usr/lib/python3/dist-packages/urllib3/util/url.py", line 409, in parse_url
    ensure_func = six.ensure_text
AttributeError: module 'six' has no attribute 'ensure_text'

**Comment by JumpAlang** [comment]
确认下docker环境，是否安装了docker-compose

**Comment by YuLong-Liang** [comment]
docker --version
Docker version 27.3.1, build ce12230

docker-compose --version
docker-compose version 1.25.0, build unknown

**Comment by YuLong-Liang** [comment]
docker-compose 换了个有版本号的，启动成功，网络连接失败
docker-compose up -d
WARN[0000] /home/CLionProjects/Jusic-Serve-Houses/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 3/3
 ✘ service_jusicMusicApi Error    context canceled                                                                                                                                                   15.5s 
 ✘ service_jusicServeHouses Error Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while a...                                15.5s 
 ✘ service_redis Error            context canceled                                                                                                                                                   15.5s 
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by JumpAlang** [comment]
看提示是你无法访问docker镜像仓库
